apiVersion: v1
kind: Pod
metadata:
  name: optracard-frontend-pod
  namespace: optracard-frontend
  labels:
    app: optracard-frontend
spec:
  containers:
    - name: optracard-frontend-container
      image: saksitboom/optracard-frontend:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80