import { useEffect, useState } from 'react';
import { Banknote, Boxes, ClipboardCheck, PackageCheck, RefreshCcw, ShoppingBag } from 'lucide-react';
import { loadAdminDashboard } from '../api/admin';
import { AdminError, AdminLoading, AdminWorkspace, formatCurrency, formatDate, StatusBadge } from '../components/AdminWorkspace';
import type { AdminDashboard } from '../types/admin';

const Stat = ({ label, value, detail, icon: Icon, tone }: { label: string; value: string; detail: string; icon: typeof Banknote; tone: string }) => (
  <div className={`rounded-2xl p-5 text-white shadow-sm ${tone}`}><div className="mb-3 flex h-9 w-9 items-center justify-center rounded-lg bg-white/20"><Icon className="h-5 w-5" /></div><p className="text-xs font-bold uppercase tracking-wider text-white/85">{label}</p><p className="mt-1 text-3xl font-extrabold">{value}</p><p className="mt-2 text-xs text-white/80">{detail}</p></div>
);

export const ADdashboard = () => {
  const [dashboard, setDashboard] = useState<AdminDashboard | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); setError(null); try { setDashboard(await loadAdminDashboard()); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Could not load dashboard data.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);

  return <AdminWorkspace currentTab="dashboard">
    <div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-bold text-slate-900">Dashboard</h1><p className="mt-1 text-sm text-slate-500">Live summary of Optracard stock, orders, and marketplace reviews.</p></div><button type="button" onClick={() => void load()} className="inline-flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-4 py-2 text-sm font-bold text-slate-700 shadow-sm"><RefreshCcw className="h-4 w-4" />Refresh</button></div>
    {error && <div className="mb-5"><AdminError message={error} onRetry={() => void load()} /></div>}
    {loading && <AdminLoading label="Loading live dashboard…" />}
    {!loading && dashboard && <div className="space-y-6">
      <div className="grid gap-4 md:grid-cols-3"><Stat label="Total revenue" value={formatCurrency(dashboard.totalRevenue)} detail="From all orders in the database" icon={Banknote} tone="bg-gradient-to-r from-amber-500 to-orange-500" /><Stat label="Total expenses" value={formatCurrency(dashboard.totalExpenses)} detail="Current cost price × ordered quantity" icon={ShoppingBag} tone="bg-gradient-to-r from-orange-600 to-red-500" /><Stat label="Estimated profit" value={formatCurrency(dashboard.totalProfit)} detail="Revenue minus current recorded costs" icon={PackageCheck} tone="bg-gradient-to-r from-indigo-500 to-violet-600" /></div>
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><p className="text-xs font-bold uppercase tracking-wide text-slate-400">Orders</p><p className="mt-2 text-2xl font-bold">{dashboard.totalOrders}</p><p className="mt-1 text-xs text-slate-500">{dashboard.totalItems} item(s)</p></div><div className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><p className="text-xs font-bold uppercase tracking-wide text-slate-400">Average order</p><p className="mt-2 text-2xl font-bold">{formatCurrency(dashboard.averageOrderValue)}</p><p className="mt-1 text-xs text-slate-500">Calculated from all orders</p></div><div className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><p className="text-xs font-bold uppercase tracking-wide text-slate-400">Official inventory</p><p className="mt-2 text-2xl font-bold">{dashboard.activeOfficialProducts}</p><p className="mt-1 text-xs text-slate-500">{dashboard.lowStockProducts} low-stock listing(s)</p></div><div className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><p className="text-xs font-bold uppercase tracking-wide text-slate-400">Marketplace listings</p><p className="mt-2 text-2xl font-bold">{dashboard.activeMarketplaceProducts}</p><p className="mt-1 text-xs text-slate-500">Active approved listings</p></div></div>
      <div className="grid gap-6 lg:grid-cols-3"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm lg:col-span-2"><div className="mb-4 flex items-center gap-2"><Boxes className="h-5 w-5 text-blue-600" /><div><h2 className="font-bold text-slate-900">Revenue & expenses by month</h2><p className="text-xs text-slate-500">Derived from recorded orders and product costs.</p></div></div>{dashboard.monthlyMetrics.length === 0 ? <p className="py-8 text-center text-sm text-slate-500">No order data is available yet.</p> : <div className="overflow-x-auto"><table className="w-full text-sm"><thead className="border-b text-left text-xs uppercase tracking-wide text-slate-400"><tr><th className="pb-3">Month</th><th className="pb-3 text-right">Revenue</th><th className="pb-3 text-right">Expenses</th><th className="pb-3 text-right">Profit</th></tr></thead><tbody>{dashboard.monthlyMetrics.map((metric) => <tr key={metric.month} className="border-b border-slate-100 last:border-0"><td className="py-3 font-semibold">{metric.month}</td><td className="py-3 text-right text-emerald-700">{formatCurrency(metric.revenue)}</td><td className="py-3 text-right text-orange-700">{formatCurrency(metric.expenses)}</td><td className="py-3 text-right font-bold">{formatCurrency(metric.revenue - metric.expenses)}</td></tr>)}</tbody></table></div>}</section><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center gap-2"><ClipboardCheck className="h-5 w-5 text-amber-600" /><h2 className="font-bold text-slate-900">Awaiting action</h2></div><div className="space-y-3"><div className="rounded-lg bg-amber-50 p-4"><p className="text-sm font-bold text-amber-900">Store Verification</p><p className="mt-1 text-3xl font-bold text-amber-700">{dashboard.pendingStoreVerifications}</p><p className="text-xs text-amber-700">seller store application(s)</p></div><div className="rounded-lg bg-blue-50 p-4"><p className="text-sm font-bold text-blue-900">Marketplace Requests</p><p className="mt-1 text-3xl font-bold text-blue-700">{dashboard.pendingMarketplaceRequests}</p><p className="text-xs text-blue-700">product listing(s)</p></div><div className="rounded-lg bg-slate-50 p-4"><p className="text-sm font-bold text-slate-800">Stock attention</p><p className="mt-1 text-3xl font-bold">{dashboard.lowStockProducts}</p><p className="text-xs text-slate-500">official listing(s) with 5 or fewer left</p></div></div></section></div>
      <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 p-5"><h2 className="font-bold text-slate-900">Recent orders</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-sm"><thead className="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Order</th><th className="px-5 py-3">Buyer</th><th className="px-5 py-3">Store</th><th className="px-5 py-3">Created</th><th className="px-5 py-3 text-right">Total</th><th className="px-5 py-3">Status</th></tr></thead><tbody>{dashboard.recentOrders.map((order) => <tr key={order.id} className="border-t border-slate-100"><td className="px-5 py-4 font-bold text-blue-600">{order.orderNumber}</td><td className="px-5 py-4">{order.buyerName}</td><td className="px-5 py-4 text-slate-600">{order.storeName ?? 'Optracard Official Store'}</td><td className="px-5 py-4 text-slate-500">{formatDate(order.createdAt)}</td><td className="px-5 py-4 text-right font-bold">{formatCurrency(order.total)}</td><td className="px-5 py-4"><StatusBadge status={order.status} /></td></tr>)}{dashboard.recentOrders.length === 0 && <tr><td colSpan={6} className="px-5 py-12 text-center text-slate-500">No orders recorded yet.</td></tr>}</tbody></table></div></section>
    </div>}
  </AdminWorkspace>;
};

export default ADdashboard;
