import { useEffect, useMemo, useState } from 'react';
import { ChevronRight, RefreshCcw, Search, Store } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { loadAdminStores } from '../api/admin';
import { AdminError, AdminLoading, AdminWorkspace, StatusBadge } from '../components/AdminWorkspace';
import type { AdminStore } from '../types/admin';

export const AD_MarketplaceProducts = () => {
  const navigate = useNavigate(); const [stores, setStores] = useState<AdminStore[]>([]); const [query, setQuery] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const load = async () => { setLoading(true); setError(null); try { setStores(await loadAdminStores('APPROVED')); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Could not load marketplace stores.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const visible = useMemo(() => { const value = query.trim().toLowerCase(); return stores.filter((store) => !value || `${store.storeName} ${store.ownerName} ${store.storeId}`.toLowerCase().includes(value)); }, [stores, query]);
  return <AdminWorkspace currentTab="marketplace-products"><div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-blue-600">Approved seller stores</p><h1 className="mt-1 text-3xl font-bold text-slate-900">Marketplace Products</h1><p className="mt-1 text-sm text-slate-500">Browse actual seller inventory by verified marketplace store.</p></div><button type="button" onClick={() => void load()} className="inline-flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold"><RefreshCcw className="h-4 w-4" />Refresh</button></div>{error && <div className="mb-5"><AdminError message={error} onRetry={() => void load()} /></div>}<div className="mb-5 rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="relative max-w-lg"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search marketplace store" className="w-full rounded-lg bg-slate-100 py-2.5 pl-10 pr-3 text-sm outline-none" /></div></div>{loading ? <AdminLoading label="Loading marketplace stores…" /> : <div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{visible.map((store) => <button key={store.storeId} type="button" onClick={() => navigate(`/admin/marketplace/stores/${store.storeId}`)} className="group rounded-2xl border border-slate-200 bg-white p-5 text-left shadow-sm transition hover:border-blue-300 hover:shadow-md"><div className="flex items-start justify-between gap-3">{store.storeProfileImage ? <img src={store.storeProfileImage} alt="" className="h-14 w-14 rounded-xl object-cover" /> : <div className="flex h-14 w-14 items-center justify-center rounded-xl bg-blue-50 text-blue-600"><Store className="h-6 w-6" /></div>}<StatusBadge status={store.storeStatus} /></div><h2 className="mt-5 text-lg font-bold text-slate-900">{store.storeName}</h2><p className="mt-1 text-sm text-slate-500">{store.ownerName || 'Store owner unavailable'}</p><p className="mt-1 text-xs text-slate-400">Store ID: {store.storeId} · {[store.district, store.province].filter(Boolean).join(', ') || 'Online'}</p><div className="mt-5 flex items-center justify-between border-t border-slate-100 pt-4"><div><p className="text-xs text-slate-400">Marketplace listings</p><p className="mt-1 text-2xl font-bold">{store.productCount}</p></div><span className="inline-flex items-center gap-1 text-sm font-bold text-blue-600">Inventory <ChevronRight className="h-4 w-4 transition group-hover:translate-x-0.5" /></span></div></button>)}{visible.length === 0 && <div className="col-span-full rounded-xl border border-slate-200 bg-white px-5 py-12 text-center text-sm text-slate-500">No approved marketplace stores found.</div>}</div>}</AdminWorkspace>;
};

export default AD_MarketplaceProducts;
