import { useEffect, useState } from 'react';
import { ClipboardList, RefreshCcw } from 'lucide-react';
import Sidebar from '../components/Sidebar';
import { loadSellerOrders, updateSellerOrderStatus } from '../api/seller';
import type { SellerOrder } from '../types/seller';

const money = (value: number) => `฿${Number(value ?? 0).toLocaleString('en-US', { minimumFractionDigits: 2 })}`;

export const OrdersManagement = () => {
  const [orders, setOrders] = useState<SellerOrder[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const load = async () => { setIsLoading(true); setError(null); try { setOrders(await loadSellerOrders()); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Could not load orders.'); } finally { setIsLoading(false); } };
  useEffect(() => { void load(); }, []);
  const updateStatus = async (order: SellerOrder, status: string) => { try { const updated = await updateSellerOrderStatus(order.orderId, status); setOrders((current) => current.map((item) => item.orderId === updated.orderId ? updated : item)); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Could not update order.'); } };
  return <div className="flex min-h-screen bg-slate-50 text-slate-800"><Sidebar currentTab="orders" /><main className="min-w-0 flex-1 p-8"><div className="mx-auto max-w-[1440px]"><div className="mb-6 flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-blue-600">My Shop</p><h1 className="mt-1 text-3xl font-bold text-slate-900">Orders Management</h1><p className="mt-1 text-sm text-slate-500">Fulfil orders containing products from your store.</p></div><button type="button" onClick={() => void load()} className="inline-flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-4 py-2 text-sm font-semibold hover:bg-slate-50"><RefreshCcw className="h-4 w-4" />Refresh</button></div>{error && <div className="mb-5 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}<div className="overflow-x-auto rounded-xl border border-slate-200 bg-white shadow-sm"><table className="w-full min-w-[850px] text-left text-sm"><thead className="border-b border-slate-200 bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-4">Order</th><th className="px-5 py-4">Buyer</th><th className="px-5 py-4">Items</th><th className="px-5 py-4">Total</th><th className="px-5 py-4">Created</th><th className="px-5 py-4">Status</th></tr></thead><tbody className="divide-y divide-slate-100">{isLoading && <tr><td colSpan={6} className="px-5 py-12 text-center text-slate-500">Loading orders…</td></tr>}{!isLoading && orders.map((order) => <tr key={order.orderId} className="hover:bg-slate-50"><td className="px-5 py-4 font-bold text-blue-600">{order.orderNumber}</td><td className="px-5 py-4"><p className="font-semibold">Buyer #{order.buyerId}</p><p className="text-xs text-slate-500">{order.recipientName || 'Pickup'}</p></td><td className="px-5 py-4"><div className="space-y-1">{order.items.map((item) => <p key={item.productId}>• {item.name} <span className="text-slate-400">×{item.quantity}</span></p>)}</div></td><td className="px-5 py-4 font-bold">{money(order.total)}</td><td className="px-5 py-4 text-slate-500">{order.createdAt ? new Date(order.createdAt).toLocaleDateString('en-GB') : '—'}</td><td className="px-5 py-4"><select value={order.status} onChange={(event) => void updateStatus(order, event.target.value)} className="rounded-lg border border-slate-200 bg-white px-2.5 py-2 text-xs font-bold"><option>Processing</option><option>Shipped</option><option>Delivered</option><option>Canceled</option></select></td></tr>)}{!isLoading && orders.length === 0 && <tr><td colSpan={6} className="px-5 py-12 text-center text-slate-500"><ClipboardList className="mx-auto mb-3 h-10 w-10 text-slate-300" />No orders for this store yet.</td></tr>}</tbody></table></div></div></main></div>;
};

export default OrdersManagement;
